import { Octokit } from "@octokit/rest";

import { ChangeEntry, GitHubIssueRef, RuleApprovalRow } from "./types";

export const DEFAULT_BOARD_REPOSITORY = {
  owner: "act-rules",
  repo: "act-board",
};

export const DEFAULT_CG_REPOSITORY = {
  owner: "act-rules",
  repo: "act-rules.github.io",
};

const WAI_RULES_BASE = "https://www.w3.org/WAI/standards-guidelines/act/rules";
const CG_RULES_BASE =
  "https://github.com/act-rules/act-rules.github.io/blob/develop/_rules";

export type RepositoryRef = {
  owner: string;
  repo: string;
};

export type BoardIssue = {
  number: number;
  title: string;
  body: string | null;
  state: "open" | "closed";
  nodeId: string;
  isPullRequest?: boolean;
};

export type SubIssue = {
  nodeId: string;
  owner: string;
  repo: string;
  number: number;
};

export type ActBoardGitHubClient = {
  listBoardIssues(repository: RepositoryRef): Promise<BoardIssue[]>;
  createBoardIssue(
    repository: RepositoryRef,
    title: string,
    body: string,
  ): Promise<BoardIssue>;
  updateBoardIssue(
    repository: RepositoryRef,
    issueNumber: number,
    update: {
      title?: string;
      body?: string;
      state?: "open" | "closed";
    },
  ): Promise<BoardIssue>;
  listSubIssues(parentNodeId: string): Promise<SubIssue[]>;
  getIssueNodeId(
    repository: RepositoryRef,
    issueNumber: number,
  ): Promise<string>;
  addSubIssue(parentNodeId: string, subIssueNodeId: string): Promise<void>;
  removeSubIssue(parentNodeId: string, subIssueNodeId: string): Promise<void>;
};

export type UpsertActBoardOptions = {
  boardRepository?: RepositoryRef;
  cgRepository?: RepositoryRef;
};

export type UpsertActBoardResult = {
  created: number;
  updated: number;
  closed: number;
  reopened: number;
  skipped: number;
  subIssuesAdded: number;
  subIssuesRemoved: number;
};

export function actBoardIssueTitle(row: RuleApprovalRow): string {
  return `[${row.ruleId}] ${row.name}`;
}

/** Return the six-character rule id used as the act-board issue upsert key. */
export function ruleIdFromActBoardTitle(title: string): string | null {
  const match = /^\[([a-z0-9]{6})\](?:\s|$)/i.exec(title);
  return match ? match[1].toLowerCase() : null;
}

export function renderActBoardIssueBody(row: RuleApprovalRow): string {
  const nonBlockers = row.issues.filter(
    (issue) => !row.blockers.some((blocker) => blocker.number === issue.number),
  );
  const lines = [
    "> [!NOTE]",
    "> This issue is generated by a bot. Do not edit this issue body; leave comments instead.",
    "",
    `**Status:** ${row.status}`,
    "",
    "## Rule links",
    "",
    `- [Proposed WAI rule](${WAI_RULES_BASE}/${row.ruleId}/proposed/)`,
  ];

  if (row.waiApproved) {
    lines.push(`- [Approved WAI rule](${WAI_RULES_BASE}/${row.ruleId}/)`);
  }
  lines.push(
    `- [Community Group rule file](${CG_RULES_BASE}/${row.filename})`,
    "",
    "## Complete implementations",
    "",
  );
  if (row.implementations.length === 0) {
    lines.push("_None._");
  } else {
    for (const implementation of [...row.implementations].sort(compareText)) {
      lines.push(`- ${implementation}`);
    }
  }

  lines.push(
    "",
    "## Changes since approval",
    "",
    `### Rule changes (${row.ruleCommitCount})`,
    "",
  );
  const ruleChanges = sortedChanges(
    row.changes.filter((change) => change.touchedRule),
  );
  appendChanges(lines, ruleChanges);

  lines.push(
    "",
    `### Definition-only changes (${row.definitionCommitCount})`,
    "",
  );
  const definitionChanges = sortedChanges(
    row.changes.filter(
      (change) =>
        !change.touchedRule && change.touchedDefinitionKeys.length > 0,
    ),
  );
  appendChanges(lines, definitionChanges);

  lines.push("", "## Open non-blocker Community Group issues", "");
  appendIssues(lines, nonBlockers);

  lines.push("", "## Open blocker Community Group issues", "");
  appendIssues(lines, row.blockers);

  return `${lines.join("\n")}\n`;
}

export async function upsertActBoardIssues(
  rows: RuleApprovalRow[],
  client: ActBoardGitHubClient,
  options: UpsertActBoardOptions = {},
): Promise<UpsertActBoardResult> {
  const boardRepository = options.boardRepository ?? DEFAULT_BOARD_REPOSITORY;
  const cgRepository = options.cgRepository ?? DEFAULT_CG_REPOSITORY;
  const result: UpsertActBoardResult = {
    created: 0,
    updated: 0,
    closed: 0,
    reopened: 0,
    skipped: 0,
    subIssuesAdded: 0,
    subIssuesRemoved: 0,
  };

  const listedIssues = (await client.listBoardIssues(boardRepository)).filter(
    (issue) => !issue.isPullRequest,
  );
  const { managedIssues, duplicateIssues } = selectManagedIssues(listedIssues);
  const unwrittenIssueNodeIds = new Set<string>();

  const rowsByRuleId = new Map(
    rows.map((row) => [row.ruleId.toLowerCase(), row]),
  );
  for (const row of [...rows].sort((a, b) =>
    a.ruleId.localeCompare(b.ruleId),
  )) {
    const ruleId = row.ruleId.toLowerCase();
    const title = actBoardIssueTitle(row);
    const body = renderActBoardIssueBody(row);
    const desiredState = row.status === "Deprecated" ? "closed" : "open";
    let issue = managedIssues.get(ruleId);

    if (!issue) {
      issue = await client.createBoardIssue(boardRepository, title, body);
      result.created += 1;
      if (desiredState === "closed") {
        issue = await client.updateBoardIssue(boardRepository, issue.number, {
          state: "closed",
        });
        result.closed += 1;
      }
      managedIssues.set(ruleId, issue);
      continue;
    }

    const update: {
      title?: string;
      body?: string;
      state?: "open" | "closed";
    } = {};
    if (issue.title !== title) update.title = title;
    if (normalizeBody(issue.body) !== normalizeBody(body)) update.body = body;
    if (issue.state !== desiredState) update.state = desiredState;

    if (Object.keys(update).length === 0) {
      unwrittenIssueNodeIds.add(issue.nodeId);
    } else {
      issue = await client.updateBoardIssue(
        boardRepository,
        issue.number,
        update,
      );
      managedIssues.set(ruleId, issue);
      if (update.state === "closed") result.closed += 1;
      else if (update.state === "open") result.reopened += 1;
      else result.updated += 1;
    }
  }

  for (const [ruleId, issue] of managedIssues) {
    if (rowsByRuleId.has(ruleId) || issue.state === "closed") continue;
    const closed = await client.updateBoardIssue(
      boardRepository,
      issue.number,
      { state: "closed" },
    );
    managedIssues.set(ruleId, closed);
    result.closed += 1;
  }

  for (const duplicate of duplicateIssues) {
    if (duplicate.state === "closed") continue;
    await client.updateBoardIssue(boardRepository, duplicate.number, {
      state: "closed",
    });
    result.closed += 1;
  }

  const desiredParentByBlocker = desiredBlockerParents(rows);
  const currentByParent = new Map<string, SubIssue[]>();
  for (const issue of managedIssues.values()) {
    currentByParent.set(issue.nodeId, await client.listSubIssues(issue.nodeId));
  }

  const desiredByParent = new Map<string, Set<string>>();
  const blockerNodeIds = new Map<number, string>();
  for (const [blockerNumber, ruleId] of desiredParentByBlocker) {
    const parent = managedIssues.get(ruleId);
    if (!parent) continue;
    let blockerNodeId = findCurrentSubIssueNodeId(
      currentByParent,
      cgRepository,
      blockerNumber,
    );
    if (!blockerNodeId) {
      blockerNodeId = await client.getIssueNodeId(cgRepository, blockerNumber);
    }
    blockerNodeIds.set(blockerNumber, blockerNodeId);
    const desired = desiredByParent.get(parent.nodeId) ?? new Set<string>();
    desired.add(blockerNodeId);
    desiredByParent.set(parent.nodeId, desired);
  }

  for (const [parentNodeId, current] of currentByParent) {
    const desired = desiredByParent.get(parentNodeId) ?? new Set<string>();
    for (const child of current) {
      if (desired.has(child.nodeId)) continue;
      await client.removeSubIssue(parentNodeId, child.nodeId);
      unwrittenIssueNodeIds.delete(parentNodeId);
      result.subIssuesRemoved += 1;
    }
  }

  for (const [parentNodeId, desired] of desiredByParent) {
    const currentIds = new Set(
      (currentByParent.get(parentNodeId) ?? []).map((child) => child.nodeId),
    );
    for (const childNodeId of desired) {
      if (currentIds.has(childNodeId)) continue;
      await client.addSubIssue(parentNodeId, childNodeId);
      unwrittenIssueNodeIds.delete(parentNodeId);
      result.subIssuesAdded += 1;
    }
  }

  result.skipped = unwrittenIssueNodeIds.size;

  return result;
}

/**
 * Pick the board issue to manage per rule id, preferring an open issue over a
 * lower-numbered closed one. Remaining issues are duplicates to close.
 */
export function selectManagedIssues(issues: BoardIssue[]): {
  managedIssues: Map<string, BoardIssue>;
  duplicateIssues: BoardIssue[];
} {
  const issuesByRuleId = new Map<string, BoardIssue[]>();
  for (const issue of [...issues].sort((a, b) => a.number - b.number)) {
    const ruleId = ruleIdFromActBoardTitle(issue.title);
    if (!ruleId) continue;
    const matches = issuesByRuleId.get(ruleId) ?? [];
    matches.push(issue);
    issuesByRuleId.set(ruleId, matches);
  }

  const managedIssues = new Map<string, BoardIssue>();
  const duplicateIssues: BoardIssue[] = [];
  for (const [ruleId, matches] of issuesByRuleId) {
    const managed =
      matches.find((issue) => issue.state === "open") ?? matches[0];
    managedIssues.set(ruleId, managed);
    duplicateIssues.push(...matches.filter((issue) => issue !== managed));
  }
  return { managedIssues, duplicateIssues };
}

/** GitHub can return bodies with CRLF or trimmed trailing whitespace. */
function normalizeBody(body: string | null | undefined): string {
  return (body ?? "").replace(/\r\n/g, "\n").trimEnd();
}

function desiredBlockerParents(rows: RuleApprovalRow[]): Map<number, string> {
  const matchingRuleIds = new Map<number, string[]>();
  for (const row of rows) {
    if (row.status === "Deprecated") continue;
    for (const blocker of row.blockers) {
      const matches = matchingRuleIds.get(blocker.number) ?? [];
      matches.push(row.ruleId.toLowerCase());
      matchingRuleIds.set(blocker.number, matches);
    }
  }

  return new Map(
    [...matchingRuleIds].map(([number, ruleIds]) => [
      number,
      [...new Set(ruleIds)].sort(compareText)[0],
    ]),
  );
}

function findCurrentSubIssueNodeId(
  currentByParent: Map<string, SubIssue[]>,
  repository: RepositoryRef,
  issueNumber: number,
): string | undefined {
  for (const children of currentByParent.values()) {
    const match = children.find(
      (child) =>
        child.owner.toLowerCase() === repository.owner.toLowerCase() &&
        child.repo.toLowerCase() === repository.repo.toLowerCase() &&
        child.number === issueNumber,
    );
    if (match) return match.nodeId;
  }
  return undefined;
}

function appendChanges(lines: string[], changes: ChangeEntry[]): void {
  if (changes.length === 0) {
    lines.push("_None._");
    return;
  }
  for (const change of changes) {
    const shortHash = change.hash.slice(0, 7);
    const commitUrl = `https://github.com/act-rules/act-rules.github.io/commit/${change.hash}`;
    const definitions =
      change.touchedDefinitionKeys.length > 0
        ? ` — definitions: ${[...change.touchedDefinitionKeys]
            .sort(compareText)
            .join(", ")}`
        : "";
    lines.push(
      `- [\`${shortHash}\`](${commitUrl}) ${escMdText(change.subject)}${definitions}`,
    );
  }
}

function appendIssues(lines: string[], issues: GitHubIssueRef[]): void {
  if (issues.length === 0) {
    lines.push("_None._");
    return;
  }
  for (const issue of [...issues].sort(
    (a, b) => a.number - b.number || compareText(a.title, b.title),
  )) {
    lines.push(
      `- [#${issue.number}: ${escMdText(issue.title)}](${issue.html_url})`,
    );
  }
}

/** Collapse whitespace and escape delimiters that would break Markdown links. */
function escMdText(text: string): string {
  return text
    .replace(/\s+/g, " ")
    .trim()
    .replace(/[[\])]/g, (character) => `\\${character}`);
}

function sortedChanges(changes: ChangeEntry[]): ChangeEntry[] {
  return [...changes].sort(
    (a, b) =>
      compareText(b.dateIso, a.dateIso) ||
      compareText(a.hash, b.hash) ||
      compareText(a.subject, b.subject),
  );
}

function compareText(a: string, b: string): number {
  return a.localeCompare(b);
}

type GraphQlSubIssueResponse = {
  node: {
    subIssues: {
      nodes: Array<{
        id: string;
        number: number;
        repository: { name: string; owner: { login: string } };
      }>;
      pageInfo: { hasNextPage: boolean; endCursor: string | null };
    };
  } | null;
};

export class OctokitActBoardClient implements ActBoardGitHubClient {
  public constructor(private readonly octokit: Octokit) {}

  public async listBoardIssues(
    repository: RepositoryRef,
  ): Promise<BoardIssue[]> {
    const issues: BoardIssue[] = [];
    const responses = this.octokit.paginate.iterator(
      this.octokit.rest.issues.listForRepo,
      {
        ...repository,
        state: "all",
        per_page: 100,
      },
    );
    for await (const response of responses) {
      for (const issue of response.data) {
        issues.push({
          number: issue.number,
          title: issue.title,
          body: issue.body ?? null,
          state: issue.state as "open" | "closed",
          nodeId: issue.node_id,
          isPullRequest: Boolean(issue.pull_request),
        });
      }
    }
    return issues;
  }

  public async createBoardIssue(
    repository: RepositoryRef,
    title: string,
    body: string,
  ): Promise<BoardIssue> {
    const { data } = await this.octokit.rest.issues.create({
      ...repository,
      title,
      body,
    });
    return boardIssueFromResponse(data);
  }

  public async updateBoardIssue(
    repository: RepositoryRef,
    issueNumber: number,
    update: {
      title?: string;
      body?: string;
      state?: "open" | "closed";
    },
  ): Promise<BoardIssue> {
    const { data } = await this.octokit.rest.issues.update({
      ...repository,
      issue_number: issueNumber,
      ...update,
    });
    return boardIssueFromResponse(data);
  }

  public async listSubIssues(parentNodeId: string): Promise<SubIssue[]> {
    const subIssues: SubIssue[] = [];
    let cursor: string | null = null;
    do {
      const response: GraphQlSubIssueResponse = await this.octokit.graphql(
        `query ActBoardSubIssues($issueId: ID!, $cursor: String) {
          node(id: $issueId) {
            ... on Issue {
              subIssues(first: 100, after: $cursor) {
                nodes {
                  id
                  number
                  repository { name owner { login } }
                }
                pageInfo { hasNextPage endCursor }
              }
            }
          }
        }`,
        { issueId: parentNodeId, cursor },
      );
      if (!response.node) break;
      for (const issue of response.node.subIssues.nodes) {
        subIssues.push({
          nodeId: issue.id,
          owner: issue.repository.owner.login,
          repo: issue.repository.name,
          number: issue.number,
        });
      }
      cursor = response.node.subIssues.pageInfo.hasNextPage
        ? response.node.subIssues.pageInfo.endCursor
        : null;
    } while (cursor);
    return subIssues;
  }

  public async getIssueNodeId(
    repository: RepositoryRef,
    issueNumber: number,
  ): Promise<string> {
    const { data } = await this.octokit.rest.issues.get({
      ...repository,
      issue_number: issueNumber,
    });
    return data.node_id;
  }

  public async addSubIssue(
    parentNodeId: string,
    subIssueNodeId: string,
  ): Promise<void> {
    await this.octokit.graphql(
      `mutation AddActBoardSubIssue($issueId: ID!, $subIssueId: ID!) {
        addSubIssue(input: { issueId: $issueId, subIssueId: $subIssueId }) {
          issue { id }
          subIssue { id }
        }
      }`,
      { issueId: parentNodeId, subIssueId: subIssueNodeId },
    );
  }

  public async removeSubIssue(
    parentNodeId: string,
    subIssueNodeId: string,
  ): Promise<void> {
    await this.octokit.graphql(
      `mutation RemoveActBoardSubIssue($issueId: ID!, $subIssueId: ID!) {
        removeSubIssue(input: { issueId: $issueId, subIssueId: $subIssueId }) {
          issue { id }
          subIssue { id }
        }
      }`,
      { issueId: parentNodeId, subIssueId: subIssueNodeId },
    );
  }
}

function boardIssueFromResponse(data: {
  number: number;
  title: string;
  body?: string | null;
  state: string;
  node_id: string;
  pull_request?: unknown;
}): BoardIssue {
  return {
    number: data.number,
    title: data.title,
    body: data.body ?? null,
    state: data.state as "open" | "closed",
    nodeId: data.node_id,
    isPullRequest: Boolean(data.pull_request),
  };
}
