export const context = {
  "@vocab": "http://www.w3.org/ns/earl#",
  earl: "http://www.w3.org/ns/earl#",
  WCAG2: "http://www.w3.org/TR/WCAG21/#",
  dct: "http://purl.org/dc/terms/",
  sch: "https://schema.org/",
  doap: "http://usefulinc.com/ns/doap#",
  testRuns: "@graph",
  name: "doap:name",
  shortDesc: "doap:shortdesc",
  release: "doap:release",
  revision: "doap:revision",
  source: "dct:source",
  title: "dct:title",
  WebPage: "sch:WebPage",
  assertedBy: { "@type": "@id" },
  outcome: { "@type": "@id" },
  mode: { "@type": "@id" },
  isPartOf: {
    "@id": "dct:isPartOf",
    "@type": "@id",
  },
  assertions: {
    "@reverse": "subject",
  },
};
